server:
  port: 8080
  servlet:
    context-path: /lyscharlie

spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      primary: db1
      datasource:
        db1:
          url: jdbc:mysql://127.0.0.1:3306/lyscharlie?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: lyscharlie
          password: 2110857
          driver-class-name: com.mysql.cj.jdbc.Driver
        db2:
          url: jdbc:mysql://127.0.0.1:3306/my_test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: lyscharlie
          password: 2110857
          driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

swagger:
  enable: true

file:
  path: /Users/liyishi/Work/data/test/upload

my:
  arr: a,b,c,d
  test:
    list:
      - liyishi
      - lyscharlie
      - lyscharlie1983
      - charlie
      - Charlie Li
      - Li Yishi
    map:
      key1: value1
      key2: value2
      key3: value3